// ROOT
export const IS_LOADING = "IS_LOADING";

// NOTIFICATIONS
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

// CITIZENS
export const SET_BSN_LIST = "SET_BSN_LIST";
export const SET_CITIZEN = "SET_CITIZEN";
export const SET_ONBOARDING_INFO = "SET_ONBOARDING_INFO";
export const SET_CONNECTION_INFO = "SET_CONNECTION_INFO";
export const SET_CREDENTIAL_OFFERS_INFO = "SET_CREDENTIAL_OFFERS_INFO";
export const SET_CREDENTIAL_OFFER_RESPONSE = "SET_CREDENTIAL_OFFER_RESPONSE";
